# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")

     crashlytics(
        api_token: 'bac2dc5f0a414db024aeea855023f3e1a1b9039a',
        build_secret: '6696555242c64c78acb71242db8e3058eb25924ee3600f52eac4e01af271b987',
        notes: release_notes
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Generate release notes"
    private_lane :release_notes do
     get_version_number
         changelog = changelog_from_git_commits
         version_number = lane_context[SharedValues::VERSION_NUMBER]
         "Release notes #{version_number} Automatic build (Last 5 PR):\n#{changelog}"
    end

end
